#
# Module manifest for module 'esPreSso'
#
# Generated by: Courtney Bodett
#
# Generated on: 5/20/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'esPreSso.psm1'

# Version number of this module.
ModuleVersion = '0.1.0'

# Supported PSEditions
# CompatiblePSEditions = @('Desktop')

# ID used to uniquely identify this module
GUID = 'e13a703c-3b7c-4537-9439-716af6a3e114'

# Author of this module
Author = 'Courtney Bodett'

# Company or vendor of this module
CompanyName = 'grey0ut'

# Copyright statement for this module
Copyright = '(c) 2025 Courtney Bodett. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A PowerShell module for keeping a Windows computer awake'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        Prerelease =  ''
        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Windows','KeepAwake','KeepAlive','Awake','Alive','Caffeine','Espresso'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/grey0ut/esPreSso/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/grey0ut/esPreSso'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}













